name= "pastebin-worker"
compatibility_date = "2023-11-28"
account_id= "0b62b8a8c958277335e65da8cc4fc644"
main = "src/index.ts"
workers_dev = false

vars = { ENVIRONMENT = "production" }
route = { pattern = "share.lumine.top", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "ba3d72d15c5047aea15de42f9708f174" },
  { binding = "PBIMGS", id ="0bbaa68bceaf4b4286da062bb6ffb971" }
]

[site]
bucket = "./static/dist"
